# This workflow will run cypress tests in this repo on chrome browser

name: Cypress browser tests with chrome

on: 
  push:
    branches: 
      - main
  workflow_dispatch   

jobs:
  browser-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '14.x.x'

    - name: Install dependencies
      run: npm install

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
    
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Phorest Cypress browser tests report
        path: test-reports    
          
      
    

   
    


          

      


 
